CREATE TABLE share (
	id INT(4) NOT NULL AUTO_INCREMENT,
	share VARCHAR(1000) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=MEMORY DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE sessions (
	session_id VARCHAR(50) NOT NULL,
	session_data VARCHAR(20000) DEFAULT NULL,
	session_last_modified DATETIME,
	PRIMARY KEY (session_id)
) ENGINE=MEMORY DEFAULT CHARSET=utf8;

CREATE TABLE logs (
	id INT(4) NOT NULL AUTO_INCREMENT,
	date DATETIME DEFAULT CURRENT_TIMESTAMP,
	level INT(2) NOT NULL,
	type VARCHAR(50) NOT NULL,
	source VARCHAR(100) DEFAULT NULL,
	user VARCHAR(100)DEFAULT NULL,
	ip VARCHAR(30)DEFAULT NULL,
	description VARCHAR(500) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;