CREATE TABLE users (
	id INT(4) NOT NULL AUTO_INCREMENT,
	login VARCHAR(50) DEFAULT NULL,
	password VARCHAR(100) DEFAULT NULL,
	firstname VARCHAR(100) DEFAULT NULL,
	lastname VARCHAR(100) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE files (
	id INT(4) NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) DEFAULT NULL,
	path VARCHAR(100) DEFAULT NULL,
	playcount INT(4) DEFAULT 0,
	vote INT(4) DEFAULT 0,
	note INT(4) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO users(login, password, firstname, lastname) VALUES ("guest", "084e0343a0486ff05530df6c705c8bb4", "Guest", "Guest");